name: mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1
  flutter_svg_provider: ^1.0.3
  qr_code_scanner: ^1.0.1
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  bloc: ^8.1.0
  injectable: ^1.5.4
  cupertino_icons: ^1.0.2
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  dio: ^4.0.6
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.0.2
  auto_route: ^5.0.2
  string_validator: ^0.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.3.2
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.5
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3


flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - assets/images/uelogo.png
    - assets/backgrounds/recomendations.png
    - assets/items/book.svg
    - assets/items/check-circle.svg
